Remove row > row nesting
sul-dlss/earthworks pull request #1401
Opened 2024-09-11 21:55 UTC by thatbudakguy

This fixes some alignment issues and removes some redundant
classes.

Closes #1318

See also https://github.com/geoblacklight/geoblacklight/pull/1607

2024-09-11 21:55 UTC, thatbudakguy commented
Easier to review with "hide whitespace" turned on.

2024-09-11 22:00 UTC, thatbudakguy commented on app/components/document_component.html.erb
> -  <%= render Geoblacklight::ViewerContainerComponent.new(document: @document) %>
See https://github.com/geoblacklight/geoblacklight/pull/1607

2024-09-16 14:37 UTC, jcoyne requested changes

2024-09-16 14:37 UTC, jcoyne commented on app/helpers/earthworks_blacklight_helper.rb
>    def show_content_classes
Can you remove this method and just override `main_content_classes` now?  https://github.com/projectblacklight/blacklight/blob/c4ce13eee7eb0819c72f35a46db4eb565e6dfaa6/app/helpers/blacklight/layout_helper_behavior.rb#L32C1-L34C8

2024-10-14 18:16 UTC, merged