Sidebar display fixes
sul-dlss/earthworks pull request #1442
Opened 2024-10-31 20:28 UTC by thatbudakguy

- **Refactor sidebar component and combine secondary portions**
- **Override the relations component to fix styling**

2024-11-01 13:01 UTC, jcoyne requested changes

2024-11-01 13:01 UTC, jcoyne commented on app/views/relation/index.html.erb
> +<%- Settings.RELATIONSHIPS_SHOWN.each do |relationship_type, rel_type_info| %>
Where is this partial called from?

2024-11-01 16:07 UTC, thatbudakguy commented on app/components/document/sidebar_component.rb
> +      components.map { |component| render component, document: }.uniq.compact_blank
Not sure – I just extracted this from the template into a method. Doesn't seem like we could conceivably duplicate a component, so I'll remove it.

2024-11-01 16:09 UTC, thatbudakguy commented
@jcoyne just so you're aware – `RelationsComponent` is a near-exact copy of Geoblacklight's `RelationsComponent`; all I wanted was to change a single CSS class in the template. If you want me to refactor it, I can, but that seems orthogonal to this PR.

2024-11-01 16:57 UTC, thatbudakguy commented
I went ahead and removed the commit in this PR dealing with `RelationsComponent`; hopefully that makes it easier to review.

2024-11-01 16:58 UTC, thatbudakguy commented on app/components/document/sidebar_component.rb
> +      components.map { |component| render component, document: }.uniq.compact_blank
Removed.

2024-11-01 16:59 UTC, thatbudakguy commented on app/components/document/sidebar_component.rb
> +    def secondary_components
Can I do that in Geoblacklight as part of a refactor to `RelationsComponent`? It seems like that's most of what you would like to see anyway. I can change the name of the method for now, if you like.

2024-11-01 18:06 UTC, jcoyne commented on app/components/document/sidebar_component.html.erb
> +    <%= filtered_components.join(separator).html_safe %>
Can we use safe_join here?
```suggestion
    <%= safe_join(filtered_components, separator) %>
```

2024-11-01 18:06 UTC, jcoyne commented on app/components/document/sidebar_component.html.erb
> +    <%= filtered_components.join(separator).html_safe %>
```suggestion
    <%= safe_join filtered_components, separator %>
```

2024-11-01 21:07 UTC, thatbudakguy commented
Thanks for the tip re: `safe_join`; updated

2024-11-04 16:41 UTC, jcoyne approved these changes

2024-11-04 16:41 UTC, merged